version: '3'

services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5435:5432"
    volumes:
      - talhao_data:/var/lib/postgis

volumes:
  talhao_data: