server:
  port: 8980

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:postgis}
    password: ${DB_PASSWORD:postgis}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql