server:
  port: 8980

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:db_talhao_manager}
    username: ${DB_USER:postgis}
    password: ${DB_PASSWORD:postgis}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql